certoraRun ./contracts/role/RoleStore.sol \
--verify RoleStore:certora/specs/RoleStore.spec \
--solc solc8.12 \
--loop_iter 2 \
--optimistic_loop \
--packages @openzeppelin=node_modules/@openzeppelin \
--solc_allow_path . \
--staging \
--rule_sanity \
--prover_args "-optimisticFallback true" \
--send_only \
--msg "GMX RoleStore" 